spring:
  config:
    activate:
      on-profile:
      - test

  devtools:
    livereload:
      enabled: false

  output:
    ansi:
      enabled: never


server:
  http2:
    enabled: false

  servlet:
    session:
      cookie:
        http-only: false
        secure: false
