spring:
  config:
    activate:
      on-profile:
      - local

  devtools:
    livereload:
      enabled: true

  output:
    ansi:
      enabled: always


server:
  port: 9990
  http2:
    enabled: false
  
  servlet:
    session:
      cookie:
        http-only: false
        secure: false


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
