spring:
  profiles:
    include:
    - ${ENV_STUDY}
  
  application:
    name: service-1
  
  main:
    web-application-type: servlet
    banner-mode: console

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-2203.local-cubi5.com/realms/keycloak-2203
          # issuer-uri: http://keycloak-1611.local-cubi5.com/auth/realms/keycloak-1611
          jwk-set-uri: http://keycloak-2203.local-cubi5.com/realms/keycloak-2203/protocol/openid-connect/certs
          # jwk-set-uri: http://keycloak-1611.local-cubi5.com/auth/realms/keycloak-1611/protocol/openid-connect/certs


server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true


logging:
  level:
    root: info


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}
    hostname: service-1


management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
        - "*"


springdoc:
  cache:
    disabled: false
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    # path: /swagger-ui.html
    # urls:
    #   - name: service-1
    #     url: /v3/api-docs
