spring:
  config:
    activate:
      on-profile:
      - dev

  devtools:
    livereload:
      enabled: true

  output:
    ansi:
      enabled: always


server:
  port: 8090
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
  
  http2:
    enabled: false


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
