spring:
  profiles:
    include:
    - ${ENV}
  
  application:
    name: service-1
  
  main:
    web-application-type: servlet
    banner-mode: console

  security:
    oauth2:
      resourceserver:
        jwt:
          # version 22.0.3, 22.0.5
          issuer-uri: http://keycloak-22.local-cubi5.com/realms/my-realm
          jwk-set-uri: http://keycloak-22.local-cubi5.com/realms/my-realm/protocol/openid-connect/certs
          
          # version 16.1.1 jboss/keycloak
          # issuer-uri: http://keycloak-1611.local-cubi5.com/auth/realms/my-realm
          # jwk-set-uri: http://keycloak-1611.local-cubi5.com/auth/realms/my-realm/protocol/openid-connect/certs


server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true


logging:
  level:
    root: info


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}
    hostname: service-1


management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
        - "*"


springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false   # intergrate in gateway
    tagsSorter: alpha
    operationsSorter: alpha
    docExpansion: none
    # path: /swagger-ui.html
    # urls:
    #   - name: service-1
    #     url: /v3/api-docs
