spring:
  config:
    activate:
      on-profile:
      - test

  devtools:
    livereload:
      enabled: false

  output:
    ansi:
      enabled: never


server:
  port: 8761
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
  
  http2:
    enabled: false
