spring:
  config:
    activate:
      on-profile:
      - dev

  devtools:
    livereload:
      enabled: true

  output:
    ansi:
      enabled: always


server:
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
  
  http2:
    enabled: false
